image: docker:latest

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn-cache

build:
  except:
    - tags
  image: $CI_REGISTRY/signageos/docker-yarn:git
  stage: build
  script:
    - export TAG=`node tools/tag-by-branch $CI_COMMIT_REF_NAME`
    - yarn config set cache-folder .yarn-cache
    - yarn --tag $TAG
    - if [ `find test* -type f -print0 | xargs -0 grep "\.only" | wc -l` -gt 0 ]; then echo "You forgot the .only in tests" && exit 1; fi
    - export VERSION=`node tools/version-next-by-branch ${CI_COMMIT_REF_NAME} ${CI_JOB_ID}`
    - node tools/version-upgrade $VERSION
    - yarn run prepublish --production
    - npm set ${NPM_REGISTRY_URL/#*:/}:_authToken=$NPM_AUTH_TOKEN
    - npm publish --ignore-scripts --tag $TAG
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        git config user.email "$GITLAB_USER_EMAIL"
        git config user.name "$GITLAB_USER_EMAIL"
        git remote set-url origin ${CI_REPOSITORY_URL/"gitlab-ci-token:$CI_JOB_TOKEN"/"$CI_REPOSITORY_PUSH_USERNAME:$CI_REPOSITORY_PUSH_TOKEN"}
        git tag v${VERSION} -a -m "$(git log --pretty="%s" `git describe --abbrev=0 --tags`...HEAD)"
        git push origin refs/tags/v${VERSION}
      fi
